repos:
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-xml
  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.1
    hooks:
      - id: pylint
        args: [--load-plugins=pylint_casthi]